package simuladorcuartofrioindustrial;

import java.awt.Color;

public class ConfigurarcionCuarto extends javax.swing.JPanel {
    
    private SimuladorCuartoFrioIndustrial framePrincipal;

    public ConfigurarcionCuarto(SimuladorCuartoFrioIndustrial framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        jScrollPane1.getViewport().setBackground(Color.white);
        restaurarTablas();
    }
    
    private void cargarTablaObjetos() {
        
        if (tablaObjetos.getModel() == null || !(tablaObjetos.getModel() instanceof javax.swing.table.DefaultTableModel)) {
            tablaObjetos.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] { "ID", "Nombre", "Límite Inferior", "Límite Superior", "Valor Actual" }
            ));
        }
        
        javax.swing.table.DefaultTableModel modelo = (javax.swing.table.DefaultTableModel) tablaObjetos.getModel();
        modelo.setRowCount(0);

        try {
            if (framePrincipal != null && framePrincipal.getGestorSensores() != null) {
            
                java.util.ArrayList<Sensor> sensores = framePrincipal.getGestorSensores().getSensores();
            
                if (sensores != null) {
                    for (Sensor sensor : sensores) {
                        
                        Object limInferior = sensor.getLimiteInferior();
                        Object limSuperior = sensor.getLimiteSuperior();
                        
                        if (sensor instanceof SensorPuerta) {
                        limInferior = 0;
                        limSuperior = 1;
                    }
                        
                        modelo.addRow(new Object[]{
                            sensor.getId(),
                            sensor.getNombre(),
                            limInferior,
                            limSuperior,
                            sensor.getValorActual()
                        });
                    }
                }
            }
            tablaObjetos.revalidate();
            tablaObjetos.repaint();
        } catch (Exception e) {
            System.out.println("Aviso: No se pudieron cargar los sensores en la tabla todavía: " + e.getMessage());
        }
    }
    
    private void cargarTablaArchivos() {
    javax.swing.table.DefaultTableModel modeloArchivos = (javax.swing.table.DefaultTableModel) tablaArchivos.getModel();
    modeloArchivos.setRowCount(0); // Limpiamos la tabla de inmediato

    String rutaTxt = "sin_nombre.txt";
    String rutaBin = "sin_nombre.bin";

    try {
            if (framePrincipal != null) {
            
                if (framePrincipal.getGestorArchivos() != null) {
                    String archivoTxt = framePrincipal.getGestorArchivos().getArchivo();
                    if (archivoTxt != null && !archivoTxt.trim().isEmpty()) {
                        rutaTxt = archivoTxt;
                    }
                }
            
                if (framePrincipal.getGestorPersistencia() != null) {
                    String archivoBin = framePrincipal.getGestorPersistencia().getArchivo();
                    if (archivoBin != null && !archivoBin.trim().isEmpty()) {
                        rutaBin = archivoBin;
                    }
                }
            }
        } catch (Exception e) {
            System.out.println("Aviso: No se pudieron extraer las rutas de los gestores aún: " + e.getMessage());
        }
        modeloArchivos.addRow(new Object[]{ rutaTxt, rutaBin });
    }
    
    private void restaurarTablas() {
        cargarTablaObjetos();
        cargarTablaArchivos();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaObjetos = new javax.swing.JTable();
        GuardarConfiguracion = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaArchivos = new javax.swing.JTable();
        SelectorSensor = new javax.swing.JComboBox<>();
        SelectorCantidadSensores = new javax.swing.JSpinner();
        AgregarSensor = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(60, 98, 85));
        setForeground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(700, 500));

        tablaObjetos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        tablaObjetos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Nombre", "Mínimo", "Máximo", "Valor"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.Double.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaObjetos);

        GuardarConfiguracion.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        GuardarConfiguracion.setText("Guardar configuraciones");
        GuardarConfiguracion.addActionListener(this::GuardarConfiguracionActionPerformed);

        tablaArchivos.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray, java.awt.Color.gray));
        tablaArchivos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Nombre archivo.txt", "Nombre archivo.bin"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tablaArchivos);

        SelectorSensor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SelectorSensor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sensor de Temperatura", "Sensor de Presion", "Sensor de Puerta" }));
        SelectorSensor.addActionListener(this::SelectorSensorActionPerformed);

        SelectorCantidadSensores.setModel(new javax.swing.SpinnerNumberModel(1, 1, 10, 1));

        AgregarSensor.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgregarSensor.setText("Agregar a la lista");
        AgregarSensor.addActionListener(this::AgregarSensorActionPerformed);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Aqui abajo tienes que poner el nombre de los archivos");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Aqui abajo puedes agregar los sensores (Cuidado de no pasarte)");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Aqui abajo tienes que cargar los parametros de los sensores");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(GuardarConfiguracion, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(144, 144, 144)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(122, 122, 122)
                        .addComponent(SelectorSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(SelectorCantidadSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(AgregarSensor)))
                .addContainerGap(159, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SelectorSensor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SelectorCantidadSensores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgregarSensor))
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(GuardarConfiguracion)
                .addContainerGap(180, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GuardarConfiguracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GuardarConfiguracionActionPerformed
        javax.swing.table.DefaultTableModel modeloObjetos = (javax.swing.table.DefaultTableModel) tablaObjetos.getModel();
        javax.swing.table.DefaultTableModel modeloArchivos = (javax.swing.table.DefaultTableModel) tablaArchivos.getModel();
    
        String nuevoTxt = "";
        String nuevoBin = "";
    
        try {
            for (int i = 0; i < modeloObjetos.getRowCount(); i++) {
                String nuevoId = modeloObjetos.getValueAt(i, 0).toString().trim();
                String nuevoNombre = modeloObjetos.getValueAt(i, 1).toString().trim();
                double limInferior = Double.parseDouble(modeloObjetos.getValueAt(i, 2).toString());
                double limSuperior = Double.parseDouble(modeloObjetos.getValueAt(i, 3).toString());
                double valActual = Double.parseDouble(modeloObjetos.getValueAt(i, 4).toString());
                
                if (nuevoId.isEmpty() || nuevoNombre.isEmpty()) {
                    throw new IllegalArgumentException("Tabla Sensores - Fila " + (i + 1) + ": El ID y el Nombre del sensor no pueden estar vacíos.");
                }

                if (limInferior >= limSuperior) {
                    throw new ParametroFueraDeRangoException(
                        "Tabla Sensores - Fila " + (i + 1) + ": El límite inferior no puede ser mayor o igual al superior."
                    );
                }
            
            }

            for (int i = 0; i < modeloArchivos.getRowCount(); i++) {
                String nombreEnTabla = modeloArchivos.getValueAt(i, 0).toString().trim();
                String tipoArchivo = modeloArchivos.getValueAt(i, 1).toString();

                if (nombreEnTabla.isEmpty()) {
                    throw new IllegalArgumentException("Tabla Archivos - Fila " + (i + 1) + ": El nombre del archivo no puede estar vacío.");
                }

                if (tipoArchivo.contains("Reporte")) {
                    if (!nombreEnTabla.endsWith(".txt")) {
                        throw new IllegalArgumentException("Tabla Archivos - Fila " + (i + 1) + ": El archivo de reporte debe incluir la extensión '.txt'");
                    }
                    nuevoTxt = nombreEnTabla;
                } else if (tipoArchivo.contains("Binario")) {
                    if (!nombreEnTabla.endsWith(".bin")) {
                        throw new IllegalArgumentException("Tabla Archivos - Fila " + (i + 1) + ": El archivo binario debe incluir la extensión '.bin'");
                    }
                    nuevoBin = nombreEnTabla;
                }
            }

            framePrincipal.setGestorArchivos(new GestorArchivos(nuevoTxt));
            framePrincipal.setGestorPersistencia(new GestorPersistenciaSensores(nuevoBin));

            javax.swing.JOptionPane.showMessageDialog(this,
                "¡Rutas de archivos guardadas en el sistema!\nLos cambios de los sensores quedan preparados en borrador.",
                "Configuración Guardada", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (ParametroFueraDeRangoException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error de coherencia en los rangos:\n" + ex.getMessage(),
                "Operación Cancelada", javax.swing.JOptionPane.ERROR_MESSAGE);
            restaurarTablas();

        } catch (NumberFormatException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Error: Has introducido texto en un campo numérico (límites o valor actual).",
                "Error de Formato", javax.swing.JOptionPane.ERROR_MESSAGE);
            restaurarTablas();

        } catch (IllegalArgumentException ex) {
            javax.swing.JOptionPane.showMessageDialog(this,
                ex.getMessage(),
                "Campos Incorrectos", javax.swing.JOptionPane.WARNING_MESSAGE);
            restaurarTablas();
        }
    }//GEN-LAST:event_GuardarConfiguracionActionPerformed

    private void SelectorSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SelectorSensorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SelectorSensorActionPerformed

    private void AgregarSensorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgregarSensorActionPerformed
        
        if (framePrincipal == null || framePrincipal.getGestorSensores() == null) {
            javax.swing.JOptionPane.showMessageDialog(this, 
                "El gestor de sensores aún no está listo.", 
                "Error de Inicialización", javax.swing.JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        String tipoSeleccionado = SelectorSensor.getSelectedItem().toString();
        int cantidad = (int) SelectorCantidadSensores.getValue();
        
        java.util.ArrayList<Sensor> listaSensores = framePrincipal.getGestorSensores().getSensores();
        
        try {
            for (int i = 0; i < cantidad; i++) {
                int numeroSiguiente = listaSensores.size() + 1;
                Sensor nuevoSensor = null;

                switch (tipoSeleccionado) {
                    case "Sensor de Temperatura":
                        nuevoSensor = new SensorTemperatura("TEMP-" + numeroSiguiente, "Temp " + numeroSiguiente, 0, 1);
                        break;

                    case "Sensor de Puerta":
                            nuevoSensor = new SensorPuerta("PUER-" + numeroSiguiente, "Puerta " + numeroSiguiente);
                        break;

                    case "Sensor de Presion":
                        nuevoSensor = new SensorPresion("PRES-" + numeroSiguiente, "Presión " + numeroSiguiente, 0, 1);
                        break;
                }

                if (nuevoSensor != null) {
                    listaSensores.add(nuevoSensor);
                }
            }

            cargarTablaObjetos();

            javax.swing.JOptionPane.showMessageDialog(this, 
                "Se han agregado " + cantidad + " sensores de " + tipoSeleccionado + " correctamente.",
                "Sensores Creados", javax.swing.JOptionPane.INFORMATION_MESSAGE);

        } catch (ParametroFueraDeRangoException ex) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error al establecer límites por defecto: " + ex.getMessage());
        }
    }//GEN-LAST:event_AgregarSensorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgregarSensor;
    private javax.swing.JButton GuardarConfiguracion;
    private javax.swing.JSpinner SelectorCantidadSensores;
    private javax.swing.JComboBox<String> SelectorSensor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tablaArchivos;
    private javax.swing.JTable tablaObjetos;
    // End of variables declaration//GEN-END:variables

}
