/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package simuladorcuartofrioindustrial.InterfazGrafica;


public class CargardorObjetos extends javax.swing.JPanel {

    private ControladorInterfaces framePrincipal;

    public CargardorObjetos(ControladorInterfaces framePrincipal) {
        this.framePrincipal = framePrincipal;
        initComponents();
        jFileChooser1.setFileFilter(new javax.swing.filechooser.FileNameExtensionFilter("Archivos de Datos (*.bin)", "bin"));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();

        setBackground(new java.awt.Color(60, 98, 85));
        setPreferredSize(new java.awt.Dimension(700, 500));

        jLabel1.setBackground(new java.awt.Color(60, 98, 85));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cargar lista de Sensores");
        jLabel1.setMaximumSize(new java.awt.Dimension(310, 30));
        jLabel1.setOpaque(true);
        jLabel1.setPreferredSize(new java.awt.Dimension(310, 30));

        jFileChooser1.setPreferredSize(new java.awt.Dimension(600, 300));
        jFileChooser1.addActionListener(this::jFileChooser1ActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(265, 265, 265)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(jFileChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jFileChooser1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFileChooser1ActionPerformed
        String comando = evt.getActionCommand();
        if (comando.equals(javax.swing.JFileChooser.APPROVE_SELECTION)) {
            java.io.File archivoSeleccionado = jFileChooser1.getSelectedFile();

            try {
                this.framePrincipal.procesarArchivoCargado(archivoSeleccionado);
                this.framePrincipal.recargarSensoresDesdeArchivoBinario();
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "¡Archivo de sensores cargado con éxito!\nOrigen: " + archivoSeleccionado.getName(),
                    "Carga Exitosa",
                    javax.swing.JOptionPane.INFORMATION_MESSAGE);
                

            } catch (Exception e) {
                javax.swing.JOptionPane.showMessageDialog(
                    this,
                    "Error al procesar la estructura del archivo binario:\n" + e.getMessage(),
                    "Error de Lectura",
                    javax.swing.JOptionPane.ERROR_MESSAGE
                );
            }

        } 
        else if (comando.equals(javax.swing.JFileChooser.CANCEL_SELECTION)) {
            javax.swing.JOptionPane.showMessageDialog(
                this,
                "Operación cancelada por el usuario.",
                "Información",
                javax.swing.JOptionPane.WARNING_MESSAGE
            );
        }
    }//GEN-LAST:event_jFileChooser1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
